title: Brett Schuchert
description: A collection of old and outdated ideas
theme: jekyll-theme-midnight
twitter_username: schuchert
github_username: schuchert
makrdown: kramdown
plugins:
  - jekyll-feed
baseurl: "/"
url: "http://schuchert.github.io"
repository: schuchert/schuchert.github.io
github: [metadata]
